version: '3'

services:
  nginx:
    build: nginx
    ports:
      - 8080:8080
    volumes:
      - ./src:/usr/share/nginx/html
    depends_on:
      - php

  php:
    build: php
    volumes:
      - ./src:/usr/share/nginx/html

  mariadb:
    image: mysql:5.7
    volumes:
      - ./mysql:/var/lib/mysql
      - ./my.cnf:/etc/mysql/my.cnf
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_DATABASE=test
      - MYSQL_USER=test
      - MYSQL_PASSWORD=test
    ports:
     - 127.0.0.1:3306:3306
